### PR TITLE
issue/31 - Remove support for iThemes ExchangeWP

### PR DESCRIPTION
**Pull request by aubreypwd**
Issue #31

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [x] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [ ] Before and after screenshots have been posted to document visual changes
* [x] Clear steps for testing the PR have been posted (as needed)

#### Testing

iThemes ExchangeWP coupons should no longer show.

### CODE REVIEW

**Comment by aubreypwd** [comment]
Works with Affiliate WP: latest, issue/4379, master
WP: 6.0
PHP: 7.4

**Review by tubiz — CHANGES_REQUESTED** [review]
`exchange` should also be removed from the list of supported integrations

https://github.com/awesomemotive/affiliatewp-show-affiliate-coupons/blob/9fe28720389702302a748ee2df1b21144efb60d4/affiliatewp-show-affiliate-coupons.php#L263

Also, we shouldn't forget to update the readme as well when packaging the release.

https://github.com/awesomemotive/affiliatewp-show-affiliate-coupons/blob/9fe28720389702302a748ee2df1b21144efb60d4/readme.txt#L32

**Comment by aubreypwd** [comment]
I assumed we would remove this at release, but it's been removed here.

**Review by tubiz — APPROVED** [review]

**Comment by aubreypwd** [comment]
Just noting that even though this got merged, we probably will not be doing a release for this since:

- It's in Core already
- We closed the wp.org plugin

@amdrew I suggest we also archive this repo...

**Pull request merged**
